# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'league_timer.ui',
# licensing of 'league_timer.ui' applies.
#
# Created: Sun Dec 15 15:39:29 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets
import sys,os

class Ui_main_window(object):

    def resource_path(self,relative_path):
        if hasattr(sys, '_MEIPASS'):
            return os.path.join(sys._MEIPASS, relative_path)
        return os.path.join(os.path.abspath("."), relative_path)

    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.setWindowModality(QtCore.Qt.NonModal)
        main_window.resize(400, 770)
        main_window.setMinimumSize(QtCore.QSize(400, 770))
        main_window.setMaximumSize(QtCore.QSize(400, 770))
        main_window.setIconSize(QtCore.QSize(40, 40))
        main_window.setAnimated(True)
        main_window.setDocumentMode(False)
        main_window.setTabShape(QtWidgets.QTabWidget.Rounded)


        
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(240, 40, 161, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(False)
        self.frame.setGeometry(QtCore.QRect(-1, 39, 401, 121))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        #self.frame.setLineWidth(3)
        #self.frame.setMidLineWidth(3)
        self.frame.setObjectName("frame")

        self.top_timer = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.top_timer.setSpacing(0)
        self.top_timer.setContentsMargins(0, 0, 0, 0)
        self.top_timer.setObjectName("top_timer")
        self.top_sum1_cd = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.top_sum1_cd.setMaximumSize(QtCore.QSize(16777215, 20))
        self.top_sum1_cd.setAlignment(QtCore.Qt.AlignCenter)
        self.top_sum1_cd.setWordWrap(False)
        self.top_sum1_cd.setMargin(0)
        self.top_sum1_cd.setIndent(0)
        self.top_sum1_cd.setObjectName("top_sum1_cd")
        self.top_timer.addWidget(self.top_sum1_cd)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.top_timer.addWidget(self.line)
        self.top_sum1_bar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_sum1_bar.sizePolicy().hasHeightForWidth())
        self.top_sum1_bar.setSizePolicy(sizePolicy)
        self.top_sum1_bar.setMaximumSize(QtCore.QSize(16777215, 5))
        self.top_sum1_bar.setProperty("value", 0)
        self.top_sum1_bar.setObjectName("top_sum1_bar")
        self.top_timer.addWidget(self.top_sum1_bar)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(180, 40, 62, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.top_spell_button = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.top_spell_button.setSpacing(0)
        self.top_spell_button.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.top_spell_button.setContentsMargins(0, 0, 0, 0)
        self.top_spell_button.setObjectName("top_spell_button")
        self.summonerspell01 = QtWidgets.QToolButton(self.verticalLayoutWidget_2)
        self.summonerspell01.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.summonerspell01.sizePolicy().hasHeightForWidth())
        self.summonerspell01.setSizePolicy(sizePolicy)
        self.summonerspell01.setBaseSize(QtCore.QSize(0, 0))
        self.summonerspell01.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.resource_path("Teleport.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.summonerspell01.setIcon(icon)
        self.summonerspell01.setIconSize(QtCore.QSize(50, 50))
        self.summonerspell01.setCheckable(False)
        self.summonerspell01.setAutoRepeat(False)
        self.summonerspell01.setAutoExclusive(False)
        self.summonerspell01.setAutoRaise(False)
        self.summonerspell01.setObjectName("summonerspell01")
        self.top_spell_button.addWidget(self.summonerspell01)
        self.summonerspell02 = QtWidgets.QToolButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.summonerspell02.sizePolicy().hasHeightForWidth())
        self.summonerspell02.setSizePolicy(sizePolicy)
        self.summonerspell02.setMinimumSize(QtCore.QSize(50, 40))
        self.summonerspell02.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(self.resource_path("Flash.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.summonerspell02.setIcon(icon1)
        self.summonerspell02.setIconSize(QtCore.QSize(50, 50))
        self.summonerspell02.setObjectName("summonerspell02")
        self.top_spell_button.addWidget(self.summonerspell02)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 40, 181, 121))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        


        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(-1, 559, 401, 121))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")

        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(-1, 429, 401, 121))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(-1, 299, 401, 121))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(-1, 169, 401, 121))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")

        self.top_button = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.top_button.setSpacing(0)
        self.top_button.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.top_button.setContentsMargins(0, 0, -1, -1)
        self.top_button.setObjectName("top_button")
        self.top_sum1_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_sum1_button.sizePolicy().hasHeightForWidth())
        self.top_sum1_button.setSizePolicy(sizePolicy)
        self.top_sum1_button.setToolTipDuration(-1)
        self.top_sum1_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.top_sum1_button.setAutoFillBackground(False)
        self.top_sum1_button.setObjectName("top_sum1_button")
        self.top_button.addWidget(self.top_sum1_button)
        self.top_sum2_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_sum2_button.sizePolicy().hasHeightForWidth())
        self.top_sum2_button.setSizePolicy(sizePolicy)
        self.top_sum2_button.setAcceptDrops(False)
        self.top_sum2_button.setAutoFillBackground(False)
        self.top_sum2_button.setObjectName("top_sum2_button")
        self.top_button.addWidget(self.top_sum2_button)

        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(240, 60, 161, 61))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.top_timer_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.top_timer_2.setSpacing(0)
        self.top_timer_2.setContentsMargins(0, 0, 0, 0)
        self.top_timer_2.setObjectName("top_timer_2")
        self.top_sum2_cd = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.top_sum2_cd.setMaximumSize(QtCore.QSize(16777215, 20))
        self.top_sum2_cd.setAlignment(QtCore.Qt.AlignCenter)
        self.top_sum2_cd.setWordWrap(False)
        self.top_sum2_cd.setMargin(0)
        self.top_sum2_cd.setIndent(0)
        self.top_sum2_cd.setObjectName("top_sum2_cd")
        self.top_timer_2.addWidget(self.top_sum2_cd)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.top_timer_2.addWidget(self.line_3)
        self.top_sum2_bar = QtWidgets.QProgressBar(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_sum2_bar.sizePolicy().hasHeightForWidth())
        self.top_sum2_bar.setSizePolicy(sizePolicy)
        self.top_sum2_bar.setMaximumSize(QtCore.QSize(16777215, 5))
        self.top_sum2_bar.setMaximum(10)
        self.top_sum2_bar.setProperty("value", 0)
        self.top_sum2_bar.setObjectName("top_sum2_bar")
        self.top_timer_2.addWidget(self.top_sum2_bar)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 170, 181, 121))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.jg_button = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.jg_button.setSpacing(0)
        self.jg_button.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.jg_button.setContentsMargins(0, 0, -1, -1)
        self.jg_button.setObjectName("jg_button")
        self.jg_sum1_button = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jg_sum1_button.sizePolicy().hasHeightForWidth())
        self.jg_sum1_button.setSizePolicy(sizePolicy)
        self.jg_sum1_button.setToolTipDuration(-1)
        self.jg_sum1_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.jg_sum1_button.setAutoFillBackground(False)
        self.jg_sum1_button.setObjectName("jg_sum1_button")
        self.jg_button.addWidget(self.jg_sum1_button)
        self.jg_sum2_button = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jg_sum2_button.sizePolicy().hasHeightForWidth())
        self.jg_sum2_button.setSizePolicy(sizePolicy)
        self.jg_sum2_button.setAcceptDrops(False)
        self.jg_sum2_button.setAutoFillBackground(False)
        self.jg_sum2_button.setObjectName("jg_sum2_button")
        self.jg_button.addWidget(self.jg_sum2_button)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(0, 300, 181, 121))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.mid_button = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.mid_button.setSpacing(0)
        self.mid_button.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.mid_button.setContentsMargins(0, 0, -1, -1)
        self.mid_button.setObjectName("mid_button")
        self.mid_sum1_button = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mid_sum1_button.sizePolicy().hasHeightForWidth())
        self.mid_sum1_button.setSizePolicy(sizePolicy)
        self.mid_sum1_button.setToolTipDuration(-1)
        self.mid_sum1_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mid_sum1_button.setAutoFillBackground(False)
        self.mid_sum1_button.setObjectName("mid_sum1_button")
        self.mid_button.addWidget(self.mid_sum1_button)
        self.mid_sum2_button = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mid_sum2_button.sizePolicy().hasHeightForWidth())
        self.mid_sum2_button.setSizePolicy(sizePolicy)
        self.mid_sum2_button.setAcceptDrops(False)
        self.mid_sum2_button.setAutoFillBackground(False)
        self.mid_sum2_button.setObjectName("mid_sum2_button")
        self.mid_button.addWidget(self.mid_sum2_button)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(0, 430, 181, 121))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.bot_button = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.bot_button.setSpacing(0)
        self.bot_button.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.bot_button.setContentsMargins(0, 0, -1, -1)
        self.bot_button.setObjectName("bot_button")
        self.bot_sum1_button = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_sum1_button.sizePolicy().hasHeightForWidth())
        self.bot_sum1_button.setSizePolicy(sizePolicy)
        self.bot_sum1_button.setToolTipDuration(-1)
        self.bot_sum1_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bot_sum1_button.setAutoFillBackground(False)
        self.bot_sum1_button.setObjectName("bot_sum1_button")
        self.bot_button.addWidget(self.bot_sum1_button)
        self.bot_sum2_button = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_sum2_button.sizePolicy().hasHeightForWidth())
        self.bot_sum2_button.setSizePolicy(sizePolicy)
        self.bot_sum2_button.setAcceptDrops(False)
        self.bot_sum2_button.setAutoFillBackground(False)
        self.bot_sum2_button.setObjectName("bot_sum2_button")
        self.bot_button.addWidget(self.bot_sum2_button)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(0, 560, 181, 121))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.sup_button = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.sup_button.setSpacing(0)
        self.sup_button.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.sup_button.setContentsMargins(0, 0, -1, -1)
        self.sup_button.setObjectName("sup_button")
        self.sup_sum1_button = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sup_sum1_button.sizePolicy().hasHeightForWidth())
        self.sup_sum1_button.setSizePolicy(sizePolicy)
        self.sup_sum1_button.setToolTipDuration(-1)
        self.sup_sum1_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sup_sum1_button.setAutoFillBackground(False)
        self.sup_sum1_button.setObjectName("sup_sum1_button")
        self.sup_button.addWidget(self.sup_sum1_button)
        self.sup_sum2_button = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sup_sum2_button.sizePolicy().hasHeightForWidth())
        self.sup_sum2_button.setSizePolicy(sizePolicy)
        self.sup_sum2_button.setAcceptDrops(False)
        self.sup_sum2_button.setAutoFillBackground(False)
        self.sup_sum2_button.setObjectName("sup_sum2_button")
        self.sup_button.addWidget(self.sup_sum2_button)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(240, 170, 161, 61))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.jg_timer = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.jg_timer.setSpacing(0)
        self.jg_timer.setContentsMargins(0, 0, 0, 0)
        self.jg_timer.setObjectName("jg_timer")
        self.jg_sum1_cd = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.jg_sum1_cd.setMaximumSize(QtCore.QSize(16777215, 20))
        self.jg_sum1_cd.setAlignment(QtCore.Qt.AlignCenter)
        self.jg_sum1_cd.setWordWrap(False)
        self.jg_sum1_cd.setMargin(0)
        self.jg_sum1_cd.setIndent(0)
        self.jg_sum1_cd.setObjectName("jg_sum1_cd")
        self.jg_timer.addWidget(self.jg_sum1_cd)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget_9)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.jg_timer.addWidget(self.line_4)
        self.jg_sum1_bar = QtWidgets.QProgressBar(self.verticalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jg_sum1_bar.sizePolicy().hasHeightForWidth())
        self.jg_sum1_bar.setSizePolicy(sizePolicy)
        self.jg_sum1_bar.setMaximumSize(QtCore.QSize(16777215, 5))
        self.jg_sum1_bar.setProperty("value", 0)
        self.jg_sum1_bar.setObjectName("jg_sum1_bar")
        self.jg_timer.addWidget(self.jg_sum1_bar)
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(240, 230, 161, 61))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.jg_timer_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.jg_timer_2.setSpacing(0)
        self.jg_timer_2.setContentsMargins(0, 0, 0, 0)
        self.jg_timer_2.setObjectName("jg_timer_2")
        self.jg_sum2_cd = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.jg_sum2_cd.setMaximumSize(QtCore.QSize(16777215, 20))
        self.jg_sum2_cd.setAlignment(QtCore.Qt.AlignCenter)
        self.jg_sum2_cd.setWordWrap(False)
        self.jg_sum2_cd.setMargin(0)
        self.jg_sum2_cd.setIndent(0)
        self.jg_sum2_cd.setObjectName("jg_sum2_cd")
        self.jg_timer_2.addWidget(self.jg_sum2_cd)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget_10)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.jg_timer_2.addWidget(self.line_5)
        self.jg_sum2_bar = QtWidgets.QProgressBar(self.verticalLayoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jg_sum2_bar.sizePolicy().hasHeightForWidth())
        self.jg_sum2_bar.setSizePolicy(sizePolicy)
        self.jg_sum2_bar.setMaximumSize(QtCore.QSize(16777215, 5))
        self.jg_sum2_bar.setProperty("value", 0)
        self.jg_sum2_bar.setObjectName("jg_sum2_bar")
        self.jg_timer_2.addWidget(self.jg_sum2_bar)
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(240, 360, 161, 61))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.mid_timer2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.mid_timer2.setSpacing(0)
        self.mid_timer2.setContentsMargins(0, 0, 0, 0)
        self.mid_timer2.setObjectName("mid_timer2")
        self.mid_sum2_cd = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.mid_sum2_cd.setMaximumSize(QtCore.QSize(16777215, 20))
        self.mid_sum2_cd.setAlignment(QtCore.Qt.AlignCenter)
        self.mid_sum2_cd.setWordWrap(False)
        self.mid_sum2_cd.setMargin(0)
        self.mid_sum2_cd.setIndent(0)
        self.mid_sum2_cd.setObjectName("mid_sum2_cd")
        self.mid_timer2.addWidget(self.mid_sum2_cd)
        self.line_7 = QtWidgets.QFrame(self.verticalLayoutWidget_11)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.mid_timer2.addWidget(self.line_7)
        self.mid_sum2_bar = QtWidgets.QProgressBar(self.verticalLayoutWidget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mid_sum2_bar.sizePolicy().hasHeightForWidth())
        self.mid_sum2_bar.setSizePolicy(sizePolicy)
        self.mid_sum2_bar.setMaximumSize(QtCore.QSize(16777215, 5))
        self.mid_sum2_bar.setProperty("value", 0)
        self.mid_sum2_bar.setObjectName("mid_sum2_bar")
        self.mid_timer2.addWidget(self.mid_sum2_bar)
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(240, 300, 161, 61))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.mid_timer = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.mid_timer.setSpacing(0)
        self.mid_timer.setContentsMargins(0, 0, 0, 0)
        self.mid_timer.setObjectName("mid_timer")
        self.mid_sum1_cd = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.mid_sum1_cd.setMaximumSize(QtCore.QSize(16777215, 20))
        self.mid_sum1_cd.setAlignment(QtCore.Qt.AlignCenter)
        self.mid_sum1_cd.setWordWrap(False)
        self.mid_sum1_cd.setMargin(0)
        self.mid_sum1_cd.setIndent(0)
        self.mid_sum1_cd.setObjectName("mid_sum1_cd")
        self.mid_timer.addWidget(self.mid_sum1_cd)
        self.line_8 = QtWidgets.QFrame(self.verticalLayoutWidget_12)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.mid_timer.addWidget(self.line_8)
        self.mid_sum1_bar = QtWidgets.QProgressBar(self.verticalLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mid_sum1_bar.sizePolicy().hasHeightForWidth())
        self.mid_sum1_bar.setSizePolicy(sizePolicy)
        self.mid_sum1_bar.setMaximumSize(QtCore.QSize(16777215, 5))
        self.mid_sum1_bar.setProperty("value", 0)
        self.mid_sum1_bar.setObjectName("mid_sum1_bar")
        self.mid_timer.addWidget(self.mid_sum1_bar)
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(240, 430, 161, 61))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.bot_timer = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.bot_timer.setSpacing(0)
        self.bot_timer.setContentsMargins(0, 0, 0, 0)
        self.bot_timer.setObjectName("bot_timer")
        self.bot_sum1_cd = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.bot_sum1_cd.setMaximumSize(QtCore.QSize(16777215, 20))
        self.bot_sum1_cd.setAlignment(QtCore.Qt.AlignCenter)
        self.bot_sum1_cd.setWordWrap(False)
        self.bot_sum1_cd.setMargin(0)
        self.bot_sum1_cd.setIndent(0)
        self.bot_sum1_cd.setObjectName("bot_sum1_cd")
        self.bot_timer.addWidget(self.bot_sum1_cd)
        self.line_9 = QtWidgets.QFrame(self.verticalLayoutWidget_13)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.bot_timer.addWidget(self.line_9)
        self.bot_sum1_bar = QtWidgets.QProgressBar(self.verticalLayoutWidget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_sum1_bar.sizePolicy().hasHeightForWidth())
        self.bot_sum1_bar.setSizePolicy(sizePolicy)
        self.bot_sum1_bar.setMaximumSize(QtCore.QSize(16777215, 5))
        self.bot_sum1_bar.setProperty("value", 0)
        self.bot_sum1_bar.setObjectName("bot_sum1_bar")
        self.bot_timer.addWidget(self.bot_sum1_bar)
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(240, 490, 161, 61))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.bot_timer_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.bot_timer_2.setSpacing(0)
        self.bot_timer_2.setContentsMargins(0, 0, 0, 0)
        self.bot_timer_2.setObjectName("bot_timer_2")
        self.bot_sum2_cd = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.bot_sum2_cd.setMaximumSize(QtCore.QSize(16777215, 20))
        self.bot_sum2_cd.setAlignment(QtCore.Qt.AlignCenter)
        self.bot_sum2_cd.setWordWrap(False)
        self.bot_sum2_cd.setMargin(0)
        self.bot_sum2_cd.setIndent(0)
        self.bot_sum2_cd.setObjectName("bot_sum2_cd")
        self.bot_timer_2.addWidget(self.bot_sum2_cd)
        self.line_10 = QtWidgets.QFrame(self.verticalLayoutWidget_14)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.bot_timer_2.addWidget(self.line_10)
        self.bot_sum2_bar = QtWidgets.QProgressBar(self.verticalLayoutWidget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_sum2_bar.sizePolicy().hasHeightForWidth())
        self.bot_sum2_bar.setSizePolicy(sizePolicy)
        self.bot_sum2_bar.setMaximumSize(QtCore.QSize(16777215, 5))
        self.bot_sum2_bar.setProperty("value", 0)
        self.bot_sum2_bar.setObjectName("bot_sum2_bar")
        self.bot_timer_2.addWidget(self.bot_sum2_bar)
        self.verticalLayoutWidget_15 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(240, 620, 161, 61))
        self.verticalLayoutWidget_15.setObjectName("verticalLayoutWidget_15")
        self.sup_timer = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_15)
        self.sup_timer.setSpacing(0)
        self.sup_timer.setContentsMargins(0, 0, 0, 0)
        self.sup_timer.setObjectName("sup_timer")
        self.sup_sum2_cd = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.sup_sum2_cd.setMaximumSize(QtCore.QSize(16777215, 20))
        self.sup_sum2_cd.setAlignment(QtCore.Qt.AlignCenter)
        self.sup_sum2_cd.setWordWrap(False)
        self.sup_sum2_cd.setMargin(0)
        self.sup_sum2_cd.setIndent(0)
        self.sup_sum2_cd.setObjectName("sup_sum2_cd")
        self.sup_timer.addWidget(self.sup_sum2_cd)
        self.line_11 = QtWidgets.QFrame(self.verticalLayoutWidget_15)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.sup_timer.addWidget(self.line_11)
        self.sup_sum2_bar = QtWidgets.QProgressBar(self.verticalLayoutWidget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sup_sum2_bar.sizePolicy().hasHeightForWidth())
        self.sup_sum2_bar.setSizePolicy(sizePolicy)
        self.sup_sum2_bar.setMaximumSize(QtCore.QSize(16777215, 5))
        self.sup_sum2_bar.setProperty("value", 0)
        self.sup_sum2_bar.setObjectName("sup_sum2_bar")
        self.sup_timer.addWidget(self.sup_sum2_bar)
        self.verticalLayoutWidget_16 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(240, 560, 161, 61))
        self.verticalLayoutWidget_16.setObjectName("verticalLayoutWidget_16")
        self.sup_timer_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_16)
        self.sup_timer_2.setSpacing(0)
        self.sup_timer_2.setContentsMargins(0, 0, 0, 0)
        self.sup_timer_2.setObjectName("sup_timer_2")
        self.sup_sum1_cd = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.sup_sum1_cd.setMaximumSize(QtCore.QSize(16777215, 20))
        self.sup_sum1_cd.setAlignment(QtCore.Qt.AlignCenter)
        self.sup_sum1_cd.setWordWrap(False)
        self.sup_sum1_cd.setMargin(0)
        self.sup_sum1_cd.setIndent(0)
        self.sup_sum1_cd.setObjectName("sup_sum1_cd")
        self.sup_timer_2.addWidget(self.sup_sum1_cd)
        self.line_12 = QtWidgets.QFrame(self.verticalLayoutWidget_16)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.sup_timer_2.addWidget(self.line_12)
        self.sup_sum1_bar = QtWidgets.QProgressBar(self.verticalLayoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sup_sum1_bar.sizePolicy().hasHeightForWidth())
        self.sup_sum1_bar.setSizePolicy(sizePolicy)
        self.sup_sum1_bar.setMaximumSize(QtCore.QSize(16777215, 5))
        self.sup_sum1_bar.setProperty("value", 0)
        self.sup_sum1_bar.setObjectName("sup_sum1_bar")
        self.sup_timer_2.addWidget(self.sup_sum1_bar)
        self.verticalLayoutWidget_17 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_17.setGeometry(QtCore.QRect(180, 170, 62, 121))
        self.verticalLayoutWidget_17.setObjectName("verticalLayoutWidget_17")
        self.top_spell_button_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_17)
        self.top_spell_button_6.setSpacing(0)
        self.top_spell_button_6.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.top_spell_button_6.setContentsMargins(0, 0, 0, 0)
        self.top_spell_button_6.setObjectName("top_spell_button_6")
        self.summonerspell03 = QtWidgets.QToolButton(self.verticalLayoutWidget_17)
        self.summonerspell03.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.summonerspell03.sizePolicy().hasHeightForWidth())
        self.summonerspell03.setSizePolicy(sizePolicy)
        self.summonerspell03.setBaseSize(QtCore.QSize(0, 0))
        self.summonerspell03.setAutoFillBackground(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(self.resource_path("Smite.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.summonerspell03.setIcon(icon2)
        self.summonerspell03.setIconSize(QtCore.QSize(50, 50))
        self.summonerspell03.setCheckable(False)
        self.summonerspell03.setAutoRepeat(False)
        self.summonerspell03.setAutoExclusive(False)
        self.summonerspell03.setAutoRaise(False)
        self.summonerspell03.setObjectName("summonerspell03")
        self.top_spell_button_6.addWidget(self.summonerspell03)
        self.summonerspell04 = QtWidgets.QToolButton(self.verticalLayoutWidget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.summonerspell04.sizePolicy().hasHeightForWidth())
        self.summonerspell04.setSizePolicy(sizePolicy)
        self.summonerspell04.setMinimumSize(QtCore.QSize(50, 40))
        self.summonerspell04.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.summonerspell04.setIcon(icon1)
        self.summonerspell04.setIconSize(QtCore.QSize(50, 50))
        self.summonerspell04.setObjectName("summonerspell04")
        self.top_spell_button_6.addWidget(self.summonerspell04)
        self.verticalLayoutWidget_18 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_18.setGeometry(QtCore.QRect(180, 300, 62, 121))
        self.verticalLayoutWidget_18.setObjectName("verticalLayoutWidget_18")
        self.top_spell_button_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_18)
        self.top_spell_button_7.setSpacing(0)
        self.top_spell_button_7.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.top_spell_button_7.setContentsMargins(0, 0, 0, 0)
        self.top_spell_button_7.setObjectName("top_spell_button_7")
        self.summonerspell05 = QtWidgets.QToolButton(self.verticalLayoutWidget_18)
        self.summonerspell05.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.summonerspell05.sizePolicy().hasHeightForWidth())
        self.summonerspell05.setSizePolicy(sizePolicy)
        self.summonerspell05.setBaseSize(QtCore.QSize(0, 0))
        self.summonerspell05.setAutoFillBackground(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(self.resource_path("Ignite.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.summonerspell05.setIcon(icon3)
        self.summonerspell05.setIconSize(QtCore.QSize(50, 50))
        self.summonerspell05.setCheckable(False)
        self.summonerspell05.setAutoRepeat(False)
        self.summonerspell05.setAutoExclusive(False)
        self.summonerspell05.setAutoRaise(False)
        self.summonerspell05.setObjectName("summonerspell05")
        self.top_spell_button_7.addWidget(self.summonerspell05)
        self.summonerspell06 = QtWidgets.QToolButton(self.verticalLayoutWidget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.summonerspell06.sizePolicy().hasHeightForWidth())
        self.summonerspell06.setSizePolicy(sizePolicy)
        self.summonerspell06.setMinimumSize(QtCore.QSize(50, 40))
        self.summonerspell06.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.summonerspell06.setIcon(icon1)
        self.summonerspell06.setIconSize(QtCore.QSize(50, 50))
        self.summonerspell06.setObjectName("summonerspell06")
        self.top_spell_button_7.addWidget(self.summonerspell06)
        self.verticalLayoutWidget_19 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_19.setGeometry(QtCore.QRect(180, 430, 62, 121))
        self.verticalLayoutWidget_19.setObjectName("verticalLayoutWidget_19")
        self.top_spell_button_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_19)
        self.top_spell_button_8.setSpacing(0)
        self.top_spell_button_8.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.top_spell_button_8.setContentsMargins(0, 0, 0, 0)
        self.top_spell_button_8.setObjectName("top_spell_button_8")
        self.summonerspell07 = QtWidgets.QToolButton(self.verticalLayoutWidget_19)
        self.summonerspell07.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.summonerspell07.sizePolicy().hasHeightForWidth())
        self.summonerspell07.setSizePolicy(sizePolicy)
        self.summonerspell07.setBaseSize(QtCore.QSize(0, 0))
        self.summonerspell07.setAutoFillBackground(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(self.resource_path("Heal.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.summonerspell07.setIcon(icon4)
        self.summonerspell07.setIconSize(QtCore.QSize(50, 50))
        self.summonerspell07.setCheckable(False)
        self.summonerspell07.setAutoRepeat(False)
        self.summonerspell07.setAutoExclusive(False)
        self.summonerspell07.setAutoRaise(False)
        self.summonerspell07.setObjectName("summonerspell07")
        self.top_spell_button_8.addWidget(self.summonerspell07)
        self.summonerspell08 = QtWidgets.QToolButton(self.verticalLayoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.summonerspell08.sizePolicy().hasHeightForWidth())
        self.summonerspell08.setSizePolicy(sizePolicy)
        self.summonerspell08.setMinimumSize(QtCore.QSize(50, 40))
        self.summonerspell08.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.summonerspell08.setIcon(icon1)
        self.summonerspell08.setIconSize(QtCore.QSize(50, 50))
        self.summonerspell08.setObjectName("summonerspell08")
        self.top_spell_button_8.addWidget(self.summonerspell08)
        self.verticalLayoutWidget_20 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_20.setGeometry(QtCore.QRect(180, 560, 62, 121))
        self.verticalLayoutWidget_20.setObjectName("verticalLayoutWidget_20")
        self.top_spell_button_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_20)
        self.top_spell_button_9.setSpacing(0)
        self.top_spell_button_9.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.top_spell_button_9.setContentsMargins(0, 0, 0, 0)
        self.top_spell_button_9.setObjectName("top_spell_button_9")
        self.summonerspell09 = QtWidgets.QToolButton(self.verticalLayoutWidget_20)
        self.summonerspell09.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.summonerspell09.sizePolicy().hasHeightForWidth())
        self.summonerspell09.setSizePolicy(sizePolicy)
        self.summonerspell09.setBaseSize(QtCore.QSize(0, 0))
        self.summonerspell09.setAutoFillBackground(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(self.resource_path("Exhaust.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.summonerspell09.setIcon(icon5)
        self.summonerspell09.setIconSize(QtCore.QSize(50, 50))
        self.summonerspell09.setCheckable(False)
        self.summonerspell09.setAutoRepeat(False)
        self.summonerspell09.setAutoExclusive(False)
        self.summonerspell09.setAutoRaise(False)
        self.summonerspell09.setObjectName("summonerspell09")
        self.top_spell_button_9.addWidget(self.summonerspell09)
        self.summonerspell10 = QtWidgets.QToolButton(self.verticalLayoutWidget_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.summonerspell10.sizePolicy().hasHeightForWidth())
        self.summonerspell10.setSizePolicy(sizePolicy)
        self.summonerspell10.setMinimumSize(QtCore.QSize(50, 40))
        self.summonerspell10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.summonerspell10.setIcon(icon1)
        self.summonerspell10.setIconSize(QtCore.QSize(50, 50))
        self.summonerspell10.setObjectName("summonerspell10")
        self.top_spell_button_9.addWidget(self.summonerspell10)

        '''
        #フレームのレイヤーが上になっているバグ


        '''
        self.chat_button = QtWidgets.QPushButton(self.centralwidget)
        self.chat_button.setGeometry(QtCore.QRect(92, 0, 191, 41))
        self.chat_button.setObjectName("chat_button")
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        main_window.setWindowTitle(QtWidgets.QApplication.translate("main_window", "LeagueTimer", None, -1))
        self.top_sum1_cd.setText(QtWidgets.QApplication.translate("main_window", "0:00", None, -1))
        self.summonerspell01.setText(QtWidgets.QApplication.translate("main_window", "...", None, -1))
        self.summonerspell02.setText(QtWidgets.QApplication.translate("main_window", "...", None, -1))
        self.top_sum1_button.setText(QtWidgets.QApplication.translate("main_window", "PushButton", None, -1))
        self.top_sum2_button.setText(QtWidgets.QApplication.translate("main_window", "PushButton", None, -1))
        self.top_sum2_cd.setText(QtWidgets.QApplication.translate("main_window", "0:00", None, -1))
        self.jg_sum1_button.setText(QtWidgets.QApplication.translate("main_window", "PushButton", None, -1))
        self.jg_sum2_button.setText(QtWidgets.QApplication.translate("main_window", "PushButton", None, -1))
        self.mid_sum1_button.setText(QtWidgets.QApplication.translate("main_window", "PushButton", None, -1))
        self.mid_sum2_button.setText(QtWidgets.QApplication.translate("main_window", "PushButton", None, -1))
        self.bot_sum1_button.setText(QtWidgets.QApplication.translate("main_window", "PushButton", None, -1))
        self.bot_sum2_button.setText(QtWidgets.QApplication.translate("main_window", "PushButton", None, -1))
        self.sup_sum1_button.setText(QtWidgets.QApplication.translate("main_window", "PushButton", None, -1))
        self.sup_sum2_button.setText(QtWidgets.QApplication.translate("main_window", "PushButton", None, -1))
        self.jg_sum1_cd.setText(QtWidgets.QApplication.translate("main_window", "0:00", None, -1))
        self.jg_sum2_cd.setText(QtWidgets.QApplication.translate("main_window", "0:00", None, -1))
        self.mid_sum2_cd.setText(QtWidgets.QApplication.translate("main_window", "0:00", None, -1))
        self.mid_sum1_cd.setText(QtWidgets.QApplication.translate("main_window", "0:00", None, -1))
        self.bot_sum1_cd.setText(QtWidgets.QApplication.translate("main_window", "0:00", None, -1))
        self.bot_sum2_cd.setText(QtWidgets.QApplication.translate("main_window", "0:00", None, -1))
        self.sup_sum2_cd.setText(QtWidgets.QApplication.translate("main_window", "0:00", None, -1))
        self.sup_sum1_cd.setText(QtWidgets.QApplication.translate("main_window", "0:00", None, -1))
        self.summonerspell03.setText(QtWidgets.QApplication.translate("main_window", "...", None, -1))
        self.summonerspell04.setText(QtWidgets.QApplication.translate("main_window", "...", None, -1))
        self.summonerspell05.setText(QtWidgets.QApplication.translate("main_window", "...", None, -1))
        self.summonerspell06.setText(QtWidgets.QApplication.translate("main_window", "...", None, -1))
        self.summonerspell07.setText(QtWidgets.QApplication.translate("main_window", "...", None, -1))
        self.summonerspell08.setText(QtWidgets.QApplication.translate("main_window", "...", None, -1))
        self.summonerspell09.setText(QtWidgets.QApplication.translate("main_window", "...", None, -1))
        self.summonerspell10.setText(QtWidgets.QApplication.translate("main_window", "...", None, -1))
        self.chat_button.setText(QtWidgets.QApplication.translate("main_window", "Chat Times", None, -1))

