# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spell_window.ui',
# licensing of 'spell_window.ui' applies.
#
# Created: Sun Dec 15 15:39:45 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets
import sys,os

class Ui_Form(object):

    def resource_path(self,relative_path):
        if hasattr(sys, '_MEIPASS'):
            return os.path.join(sys._MEIPASS, relative_path)
        return os.path.join(os.path.abspath("."), relative_path)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 242)
        Form.setMinimumSize(QtCore.QSize(400, 242))
        Form.setMaximumSize(QtCore.QSize(400, 242))
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 20, 336, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton_1 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_1.setMinimumSize(QtCore.QSize(60, 60))
        self.toolButton_1.setMaximumSize(QtCore.QSize(50, 50))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.resource_path("Barrier.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_1.setIcon(icon)
        self.toolButton_1.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_1.setObjectName("toolButton_1")
        self.gridLayout.addWidget(self.toolButton_1, 0, 0, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_3.setMinimumSize(QtCore.QSize(60, 60))
        self.toolButton_3.setMaximumSize(QtCore.QSize(50, 50))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(self.resource_path("Cleanse.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon1)
        self.toolButton_3.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout.addWidget(self.toolButton_3, 0, 2, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_2.setMinimumSize(QtCore.QSize(60, 60))
        self.toolButton_2.setMaximumSize(QtCore.QSize(50, 50))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(self.resource_path("Exhaust.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon2)
        self.toolButton_2.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout.addWidget(self.toolButton_2, 0, 1, 1, 1)
        self.toolButton_4 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_4.setMinimumSize(QtCore.QSize(60, 60))
        self.toolButton_4.setMaximumSize(QtCore.QSize(50, 50))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(self.resource_path("Flash.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon3)
        self.toolButton_4.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout.addWidget(self.toolButton_4, 0, 3, 1, 1)
        self.toolButton_9 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_9.setMinimumSize(QtCore.QSize(60, 60))
        self.toolButton_9.setMaximumSize(QtCore.QSize(50, 50))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(self.resource_path("Teleport.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_9.setIcon(icon4)
        self.toolButton_9.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_9.setObjectName("toolButton_9")
        self.gridLayout.addWidget(self.toolButton_9, 1, 3, 1, 1)
        self.toolButton_8 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_8.setMinimumSize(QtCore.QSize(60, 60))
        self.toolButton_8.setMaximumSize(QtCore.QSize(50, 50))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(self.resource_path("Smite.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_8.setIcon(icon5)
        self.toolButton_8.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_8.setObjectName("toolButton_8")
        self.gridLayout.addWidget(self.toolButton_8, 1, 2, 1, 1)
        self.toolButton_6 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_6.setMinimumSize(QtCore.QSize(60, 60))
        self.toolButton_6.setMaximumSize(QtCore.QSize(50, 50))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(self.resource_path("Heal.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_6.setIcon(icon6)
        self.toolButton_6.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_6.setObjectName("toolButton_6")
        self.gridLayout.addWidget(self.toolButton_6, 1, 0, 1, 1)
        self.toolButton_7 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_7.setMinimumSize(QtCore.QSize(60, 60))
        self.toolButton_7.setMaximumSize(QtCore.QSize(50, 50))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(self.resource_path("Ignite.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_7.setIcon(icon7)
        self.toolButton_7.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_7.setObjectName("toolButton_7")
        self.gridLayout.addWidget(self.toolButton_7, 1, 1, 1, 1)
        self.toolButton_5 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_5.setMinimumSize(QtCore.QSize(60, 60))
        self.toolButton_5.setMaximumSize(QtCore.QSize(50, 50))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(self.resource_path("Ghost.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon8)
        self.toolButton_5.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout.addWidget(self.toolButton_5, 0, 4, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.toolButton_1.setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.toolButton_3.setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.toolButton_2.setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.toolButton_4.setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.toolButton_9.setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.toolButton_8.setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.toolButton_6.setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.toolButton_7.setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.toolButton_5.setText(QtWidgets.QApplication.translate("Form", "...", None, -1))

